InOut/urls.py
from django.urls import path
from . import views

app_name = "in_out"

urlpatterns = [
    path('', views.pemasukan, name = 'pemasukan'),
    path('pengeluaran/', views.pengeluaran, name ='pengeluaran')
]

TK1PPW/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homePage.urls")),
    path('riwayat/', include("InOut.urls")),
    path('promolist/', include("promolist.urls")),
    path('wishlist/', include('wishlist.urls')), 
    path('jadwal/', include('jadwal.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InOut/models.py
from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.
class Saldo(models.Model):
    saldo = models.BigIntegerField(default = 0)

class Pengeluaran_Pemasukan(models.Model):
    tanggal = models.DateField(auto_now_add=True)
    jam = models.TimeField(auto_now_add=True)
    keterangan = models.CharField(default = "", max_length = 100)
    status = models.CharField(default = "",max_length = 10)
    nominal = models.IntegerField(default = 0, validators=[MaxValueValidator(9999999999)])
    saldo = models.BigIntegerField(default = 0)

InOut/forms.py
from django import forms
from . import models

class Rincian(forms.ModelForm):
    class Meta:
        model = models.Pengeluaran_Pemasukan
        fields = ['keterangan', 'nominal']

class Create_Saldo(forms.ModelForm):
    class Meta:
        model = models.Saldo
        fields = ['saldo']

InOut/views.py
from django.shortcuts import render
from . import forms
from . models import Pengeluaran_Pemasukan, Saldo
from django.shortcuts import redirect

# Create your views here.
def pemasukan(request):
    counter = 0
    for s in Saldo.objects.all() :
        counter = counter + 1
    if counter == 0:
        data = {'saldo':0}
        saldo = forms.Create_Saldo(data)
        if saldo.is_valid():
            saldo.save()

    saldo = Saldo.objects.all()[0]
    if request.method == 'POST':
        form = forms.Rincian(request.POST)
        if form.is_valid():
            objectRincian = form.save(commit=False)
            objectRincian.status = 'Pemasukan'
            objectRincian.saldo = saldo.saldo + objectRincian.nominal
            objectRincian.save()
            saldo.saldo =  objectRincian.saldo
            saldo.save()
            return redirect('in_out:pemasukan')
    else:
        form = forms.Rincian()
    dataDompet = Pengeluaran_Pemasukan.objects.all().order_by('-tanggal', '-jam')
    context = {
        'form':form,
        'dataDompet':dataDompet,
        'saldo':saldo
    }
    return render(request, 'pemasukan.html', context)

def pengeluaran(request):
    counter = 0
    for s in Saldo.objects.all() :
        counter = counter + 1
    if counter == 0:
        data = {'saldo':0}
        saldo = forms.Create_Saldo(data)
        if saldo.is_valid():
            saldo.save()

    saldo = Saldo.objects.all()[0]
    if request.method == 'POST':
        form = forms.Rincian(request.POST)
        if form.is_valid():
            objectRincian = form.save(commit=False)
            objectRincian.status = 'Pengeluaran'
            objectRincian.saldo = saldo.saldo - objectRincian.nominal
            objectRincian.save()
            saldo.saldo =  objectRincian.saldo
            saldo.save()
            return redirect('in_out:pemasukan')
    else:
        form = forms.Rincian()
    dataDompet = Pengeluaran_Pemasukan.objects.all().order_by('-tanggal', '-jam')
    context = {
        'form':form,
        'dataDompet':dataDompet,
        'saldo':saldo
    }
    return render(request, 'pengeluaran.html', context)

def getSaldo():
    counter = 0
    for s in Saldo.objects.all() :
        counter = counter + 1
    if counter == 0:
        data = {'saldo':0}
        saldo = forms.Create_Saldo(data)
        if saldo.is_valid():
            saldo.save()
    saldo = Saldo.objects.all()[0]
    return saldo

InOut/templates/pemasukan.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'InOut.css' %}">
{% endblock %}

{% block content %}

<div id="Title">
    <p>Masukan data pemasukan / pengeluaran kamu disini</p>
</div>

{% if saldo.saldo < 0 %}
    <div id="Warning">
        <h2>PERINGATAN!</h2>
        <p>Pengeluaran kamu telah melebihi 
            uang yang kamu miliki! Segera
            atur pengeluaranmu!
        </p>
    </div>
{% endif %}

<form class="dataForm" action="{% url 'in_out:pemasukan' %}" method="POST">
    <div id="keluarMasuk">
        <p id="current">Pemasukan</p>
        <a id="movePage" href="{% url 'in_out:pengeluaran' %}">Pengeluaran</a>
    </div>
    {% if saldo.saldo < 9999999999 %}
        <div id="formInput">
            <table>
                {% csrf_token %}
                <div id="inputFormData">
                    <label>Catatan: </label>
                    {{form.keterangan}}
                    <label>Nominal: </label>
                    {{form.nominal}}
                </div>
            </table>
        </div>
        <div id="buttonSumbit">
            <input class="submitButton" type="submit" value="Simpan">
        </div>
    {% else %}
        <div id="saldoLewat">
            <p>Saldomu melewati batas yang dapat ditampung DompetQ :(</p>
        </div>
    {% endif %}
</form>

<div id="tabelRiwayat">
    <p id="Riwayat">Riwayat</p>
    <div id="tabelTransaksi">
        <div class="keteranganBar">
            <p class="tanggal">Tanggal</p>
            <p class="catatan">Catatan</p>
            <p class="jenis">Jenis</p>
            <p class="nominal">Nominal</p>
            <p class="saldo">Saldo</p>
        </div>
        <form class="getData" action="{url 'in_out:pemasukan' %}" method ="GET">
            {% for d in dataDompet %}
                <div class="transaksi">
                    {% if d.status == "Pemasukan" %}
                    <div class="pemasukanData">
                        <p class="tanggal">{{d.tanggal}}</p>
                        <p class="catatan">{{d.keterangan}}</p>
                        <p class="jenis">{{d.status}}</p>
                        <p class="nominal">Rp{{d.nominal}}</p>
                        <p class="saldo">Rp{{d.saldo}}</p>
                    </div>
                    {% else %}
                    <div class="pengeluaranData">
                        <p class="tanggal">{{d.tanggal}}</p>
                        <p class="catatan">{{d.keterangan}}</p>
                        <p class="jenis">{{d.status}}</p>
                        <p class="nominal">Rp{{d.nominal}}</p>
                        <p class="saldo">Rp{{d.saldo}}</p>
                    </div>
                    {% endif %}
                </div>
            {% endfor %}
        </form>
    </div>
</div>

{% endblock %}

InOut/templates/pengeluaran.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'InOut.css' %}">
{% endblock %}

{% block content %}

<div id="Title">
    <p>Masukan data pemasukan / pengeluaran kamu disini</p>
</div>
{% if saldo.saldo < 0 %}
    <div id="Warning">
        <h2>PERINGATAN!</h2>
        <p>Pengeluaran kamu telah melebihi 
            uang yang kamu miliki! Segera
            atur pengeluaranmu!
        </p>
    </div>
{% endif %}
<form class="dataForm" action="{% url 'in_out:pengeluaran' %}" method="POST">
    <div id="keluarMasuk">
        <a id="movePage" href="{% url 'in_out:pemasukan' %}">Pemasukan</a>
        <p id="current">Pengeluaran</p>
    </div>
    {% if saldo.saldo > -9999999999 %}
        <div id="formInput">
            <table>
                {% csrf_token %}
                <div id="inputFormData">
                    <label>Catatan: </label>
                    {{form.keterangan}}
                    <label>Nominal: </label>
                    {{form.nominal}}
                </div>
            </table>
        </div>
        <div id="buttonSumbit">
            <input class="submitButton" type="submit" value="Simpan">
        </div>
    {% else %}
        <div id="saldoLewat">
            <p>Saldomu melewati batas yang dapat ditampung DompetQ :(</p>
        </div>
    {% endif %}
</form>

<div id="tabelRiwayat">
    <p id="Riwayat">Riwayat</p>
    <div id="tabelTransaksi">
        <div class="keteranganBar">
            <p class="tanggal">Tanggal</p>
            <p class="catatan">Catatan</p>
            <p class="jenis">Jenis</p>
            <p class="nominal">Nominal</p>
            <p class="saldo">Saldo</p>
        </div>
        <form class="getData" action="{url 'in_out:pemasukan' %}" method ="GET">
            {% for d in dataDompet %}
                <div class="transaksi">
                    {% if d.status == "Pemasukan" %}
                    <div class="pemasukanData">
                        <p class="tanggal">{{d.tanggal}}</p>
                        <p class="catatan">{{d.keterangan}}</p>
                        <p class="jenis">{{d.status}}</p>
                        <p class="nominal">Rp{{d.nominal}}</p>
                        <p class="saldo">Rp{{d.saldo}}</p>
                    </div>
                    {% else %}
                    <div class="pengeluaranData">
                        <p class="tanggal">{{d.tanggal}}</p>
                        <p class="catatan">{{d.keterangan}}</p>
                        <p class="jenis">{{d.status}}</p>
                        <p class="nominal">Rp{{d.nominal}}</p>
                        <p class="saldo">Rp{{d.saldo}}</p>
                    </div>
                    {% endif %}
                </div>
            {% endfor %}
        </form>
    </div>
</div>

{% endblock %}